### ISSUE TITLE
Roadmap for LuckPermsWeb v2

### ISSUE THREAD

**Issue by kynetp** [lucko/LuckPermsWeb#92]
Here are some things that I have planned for LuckPermsWeb v2
# Technical Roadmap
- [ ] TypeScript Backend
- [ ] Styling with css preprocessor (SCSS)
- [ ] Axios Rest Client
- [ ] I18N for translation into different languages
- [ ] Vue.JS Frontend Framework
- [ ] Progressive Web App for offline usage
- [ ] DevExtreme Components for a professional look on the controls
- [ ] Bootstrap for Layout and Theming
- [ ] Instructions for collaborating on this project

# Feature Roadmap
- [ ] All features from current editor are still working
- [ ] Preview/undoing of web editor changes #34
- [ ] Display the kind of error when loading fails #38
- [ ] Add ability to edit more options and group setup #39
- [ ] Add / delete groups from within the editor #41
- [ ] Request: reposition permissions in web + categories #42
- [ ] Organize displayed groups by tracks #43
- [ ] Permission Optimisation Suggester #49
- [ ] Side by side view #50
- [ ] Better editor for large # of groups. #56
- [ ] Multi-language support #80
- [ ] Drag and Drop Permission nodes between groups to other "tabs" #86

You can follow the progress being made here: https://github.com/kynetp/

This will be a complete rewrite of this editor. Screenshots of the progress will be posted regular in this post. 

I expect this to be done within 60 days. After this I will maintain this project and add new features.

**Comment by Turbotailz** [comment]
Well, [this is awkward](https://github.com/Turbotailz/LuckPermsWeb).

**Comment by kynetp** [comment]
Ow man... Glad I posted this before starting heavy work. Good luck with that one.

**Comment by BrainStone** [comment]
I mean once Turbo finished the v2, you are free to work on a v3 ;)

**Comment by kynetp** [comment]
Whats the point on recreating a v3 when v2 has everything built in it ? :(

**Comment by 8MiYile** [comment]
what???

**Comment by BrainStone** [comment]
Pretty sure it won't have everything on that list. Especially stuff like translations.  
But in any case you are free to make it or not. And you are also free to help out Turbo. I'm sure he'll apprechiate the help.
